runtime: nodejs18
runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "22"

handlers:
- url: /static
  static_dir: build/static
- url: /  # This handler will match the homepage
  static_files: build/index.html
  upload: build/index.html
- url: /(.*)  # This handler will match all other files
  static_files: build/\1
  upload: build/(.*)