steps:
- name: 'node:latest'
  entrypoint: 'npm'
  args: ['install']

- name: 'node:latest'
  entrypoint: 'npm'
  args: ['run', 'build']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--project=$PROJECT_ID']
  env:
  - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'
  - 'CLOUDSDK_APP_DEPLOY_REGION=$LOCATION'
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
artifacts:
  objects:
    location: 'gs://$PROJECT_NUMBER-docusaurus-bucket'
    paths: ['build/**']
